### ISSUE TITLE
ValuesError: Conflicting values found for entity 'run' in filename

### ISSUE THREAD

**Issue by giulia-berto** [brainlife/app-fmriprep#18]
With version 20.2.0 I got this error (similar to that reported in issue #2 ):
```Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 10, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/run.py", line 17, in main
    parse_args()
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/parser.py", line 592, in parse_args
    config.from_dict(vars(opts))
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/config.py", line 612, in from_dict
    execution.load(settings)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/config.py", line 218, in load
    cls.init()
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/config.py", line 448, in init
    re.compile(r"^\."),
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/layout.py", line 155, in __init__
    indexer(self)
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/index.py", line 111, in __call__
    self._index_metadata()
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/index.py", line 427, in _index_metadata
    md_val))
bids.exceptions.BIDSConflictingValuesError: Conflicting values found for entity 'run' in filename /export/prod/5fce6985d89d01c47c5d0a9a/5fcea2b4d89d01b3be5d39ad/bids/sub-01/func/sub-01_task-rest_echo-3_run-01_bold.nii.gz (value='1') versus its JSON sidecar (value='01'). Please reconcile this discrepancy.```

**Comment by soichih** [comment]
Ref > https://github.com/bids-standard/pybids/issues/687#issuecomment-740685721

I've made an update to bl2bids script so that it will remove run from the json written out to bids directory (also convert run metadata field to an integer before using it as file name). Please try rerunning.

**Comment by giulia-berto** [comment]
thank you @soichih, that issue is solved now, however now there is another one:
 ```Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/workflow.py", line 84, in build_workflow
    retval["workflow"] = init_fmriprep_wf()
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 64, in init_fmriprep_wf
    single_subject_wf = init_single_subject_wf(subject_id)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 304, in init_single_subject_wf
    func_preproc_wf = init_func_preproc_wf(bold_file)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/bold/base.py", line 167, in init_func_preproc_wf
    config.loggers.warning(
AttributeError: type object 'loggers' has no attribute 'warning'
```

**Comment by soichih** [comment]
This looks like a fmriprep issue. Can you open a github issue here > https://github.com/nipreps/fmriprep/issues/new/choose

**Comment by giulia-berto** [comment]
ok done https://github.com/nipreps/fmriprep/issues/2344

**Comment by giulia-berto** [comment]
that was already asked https://github.com/nipreps/fmriprep/issues/2296
However I don't see any docker container with a more recent version than 20.2.0, I'll try with another version.

**Comment by effigies** [comment]
Apologies, the docker container is now `nipreps/fmriprep`, not `poldracklab/fmriprep`. We did not communicate this properly.

**Comment by giulia-berto** [comment]
Thanks, we are using `nipreps/fmriprep` now.
